### ISSUE TITLE
A few questions about code functionality

### ISSUE THREAD

**Issue by Urazome2021** [qzhou-2020/HEC_MATH_80624_project#6]
I would like to ask, now I have a set of error data of wind power output, they are distributed randomly on the plane, I delineate a range as an uncertain set, how can I use your code to substitute my data? Then I would like to ask, what functions do each of your subscripts implement? thanks for your answer

**Comment by Urazome2021** [comment]
I ran main.py, but I don't understand the meaning of the workspace and what it outputs, thank you for your answer

**Comment by qzhou-2020** [comment]
> 

This code provides an oracle-based RO solver. You may find the original idea from:

Aharon Ben-Tal, Elad Hazan, Tomer Koren, and Shie Mannor. Oracle-based robust optimization via online learning. Operations Research, 63(3):628–638, May 2015b. doi: 10.1287/opre.2015.1374. URL https://doi.org/10.1287/opre.2015.1374.

**Comment by qzhou-2020** [comment]
This code provides an oracle-based RO solver. You may find the original idea from:

Aharon Ben-Tal, Elad Hazan, Tomer Koren, and Shie Mannor. Oracle-based robust optimization via online learning. Operations Research, 63(3):628–638, May 2015b. doi: 10.1287/opre.2015.1374. URL https://doi.org/10.1287/opre.2015.1374.

**Comment by qzhou-2020** [comment]
> I ran main.py, but I don't understand the meaning of the workspace and what it outputs, thank you for your answer

You may want to see the test_code.py for an example. The main.py is only for our term project.

**Comment by Urazome2021** [comment]
ok, thanks, but I try to run the test_code.py. It doesn't have anything. I don't know what's wrong.

**Comment by Urazome2021** [comment]
Do you mean that this code must run with Oracle, if there is no code it will still run but will not output any results?
